version: '3'

services:
  database:
    image: 'postgres:latest'
    container_name: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data